---
- name: Get list of installed plugins.
  command: >
    ./bin/logstash-plugin list
    chdir=/usr/share/logstash
  register: logstash_plugins_list
  changed_when: false

- name: Install configured plugins.
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir=/usr/share/logstash
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash

- name: Install X-Pack.
  become: true
  command: /usr/share/logstash/bin/logstash-plugin install x-pack
  when: logstash_xpack_enabled
  notify: restart logstash
